### login admin
POST https://matura-api.it4u.app/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "john@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### login user
POST https://matura-api.it4u.app/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "mary@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### get user by id
GET https://matura-api.it4u.app/api/v1/users/1
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}


### get information about me
GET https://matura-api.it4u.app/api/v1/users/me
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### create user
POST https://matura-api.it4u.app/api/v1/users
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "email": "rafal@gmail.com",
  "username": "Rafal Nowak",
  "password": "userPass",
  "role": "ADMIN"
}

### delete user
DELETE https://matura-api.it4u.app/api/v1/users/88
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get user by id
GET https://matura-api.it4u.app/api/v1/users/1
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get all users
GET https://matura-api.it4u.app/api/v1/users
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get all users
GET https://matura-api.it4u.app/api/v1/users?page=0&size=80
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get pending task
GET https://matura-api.it4u.app/api/v1/users/2/pendingTask?templateId=1
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}