server:
  port: 0

spring:
  application:
    name: matura-api
  datasource:
    url: jdbc:postgresql://localhost:5332/defaultdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true