management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            probes:
                enabled: true
    health:
        livenessState:
            enabled: true
        readinessState:
            enabled: true
spring:
    application:
        name: matura-api
    datasource:
        url: jdbc:postgresql://db-postgresql-ams3-17133-do-user-17810680-0.g.db.ondigitalocean.com:25060/defaultdb?sslmode=require&sslrootcert=/etc/ssl/certs/ca.crt
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true

server:
    port: 8080
    error:
        include-message: always

kafka:
    bootstrap-servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
    group-id: group_json
    trusted-packages: "*"
    command-topic: Kafka_Task_json
    report-topic: Kafka_Task_Report_json

volume:
    path: /tmp/files/