management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
spring:
  #    profiles:
  #        active: prod-test
  application:
    name: matura-api
  datasource:
    url: jdbc:postgresql://localhost:5432/defaultdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  kafka:
    consumer:
      group-id: matura-api-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      isolation-level: read_committed  # Używaj tylko skommitowanych danych

server:
  port: 8080
  error:
    include-message: always

kafka:
  bootstrap-servers: kafka:9092
  group-id: group_json
  trusted-packages: "*"
  command-topic: kafka-task-json
  report-topic: kafka-task-report-json

volume:
  path: /tmp/files/
