management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

spring:
  application:
    name: worker

server:
  port: 8080
  error:
    include-message: always

kafka:
  bootstrap-servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  group-id: group_json
  trusted-packages: "*"
  command-topic: Kafka_Task_json
  report-topic: Kafka_Task_Report_json

volume:
  path: /tmp/files/
