management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

spring:
  application:
    name: worker
  kafka:
    consumer:
      group-id: matura-worker-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      isolation-level: read_committed
      max-poll-records: 1
      heartbeat-interval: 1000
      session-timeout-ms: 10000
      max-poll-interval-ms: 300000
    listener:
      type: single
      ack-mode: manual
    producer:
      acks: all
      transaction-id-prefix: worker-tx-

server:
  port: 8080
  error:
    include-message: always

kafka:
  bootstrap-servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  group-id: group_json
  trusted-packages: "*"
  command-topic: kafka-task-json
  report-topic: kafka-task-report-json

volume:
  path: /tmp/files/
