apiVersion: apps/v1
kind: Deployment
metadata:
  name: matura-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matura
  template:
    metadata:
      labels:
        app: matura
    spec:
      containers:
        - name: matura
          image: rafalnowak444/matura-api:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres.spark-apps.svc.cluster.local:5432/defaultdb"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"
          volumeMounts:
            - name: file-storage  # Nazwa woluminu, który dodajemy
              mountPath: /tmp/files  # Ścieżka wewnątrz kontenera (zgodna z application.yml)
      volumes:
        - name: file-storage  # Nazwa woluminu
          persistentVolumeClaim:
            claimName: matura-pvc  # Nazwa PersistentVolumeClaim, który wcześniej stworzyliśmy
---
apiVersion: v1
kind: Service
metadata:
  name: matura-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: matura
