apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matura-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Określ wymaganą przestrzeń dyskową (można dostosować)
  storageClassName: do-block-storage
