apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matura-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: shared-storage
