apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: ZG9hZG1pbg==   # Zakoduj "doadmin" w base64
  password: password-in-base64   # Zakoduj swoje hasło w base64
