name: CD - Build and Deploy Custom Temurin Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-custom-temurin-docker.yml
      - Dockerfile  # Sprawdza zmiany w Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%Y.%m.%d.%H.%M.%S')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform=linux/amd64,linux/arm64 \
            -t "${{ secrets.DOCKERHUB_USERNAME }}/custom-temurin-docker:${{ steps.build-number.outputs.BUILD_NUMBER }}" \
            -t "${{ secrets.DOCKERHUB_USERNAME }}/custom-temurin-docker:latest" \
            --push \
            .

      - name: Logout from Docker Hub
        run: docker logout
