name: CD - Deploy Worker Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/worker/**
      - .github/workflows/worker-backend-cd.yml

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend/worker

    steps:
      # Sprawdzenie repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

      # Logowanie do Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # Ustawienie numeru buildu
      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%Y.%m.%d.%H.%M.%S')" >> $GITHUB_OUTPUT

      # Budowanie obrazu Docker i jego wypchnięcie z unikalnym tagiem
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform=linux/amd64,linux/arm64 \
            -t "${{ vars.DOCKERHUB_USERNAME }}/matura-worker:${{ steps.build-number.outputs.BUILD_NUMBER }}" \
            -t "${{ vars.DOCKERHUB_USERNAME }}/matura-worker:latest" \
            --push \
            .

      - name: Logout from Docker Hub
        run: docker logout

      # Logowanie do DigitalOcean
      - name: Login to DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # Logowanie do Kubernetes na DigitalOcean
      - name: Fetch Kubernetes Credentials
        run: doctl kubernetes cluster kubeconfig save ${{ vars.DIGITALOCEAN_K8S_CLUSTER }}

      # Zmiana obrazu w pliku deployment-matura-worker.yaml w folderze ./deployment
      - name: Update deployment-matura-worker.yaml with new image tag
        run: |
          sed -i 's@image: rafalnowak444/matura-worker:.*@image: rafalnowak444/matura-worker:${{ steps.build-number.outputs.BUILD_NUMBER }}@' ../../deployment/deployment-matura-worker.yaml

      # Wykonanie kubectl apply dla deployment-matura-worker.yaml (z folderu ./deployment)
      - name: Apply Kubernetes Deployment
        run: kubectl apply -f ../../deployment/deployment-matura-worker.yaml
